name: CI_on_ubuntu-16.04

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: updating available system dependencies
      run: sudo apt-get update
    - name: installing system dependencies
      run: sudo apt-get install -y build-essential pkg-config automake libncurses5-dev autotools-dev libparted-dev dmidecode clang-format-5.0
    - name: creating autoconf files
      run: ./init.sh
    - name: configuring
      run: ./configure CFLAGS='-O0 -g -Wall -Wextra'
    - name: compiling
      run: make
    # Changing the path should no longer be necessary when clang-format6 is installed.
    - name: verifying code style
    # TODO use check-format when all the code has been formatted.
    #   run: export PATH=$PATH:/usr/lib/llvm-5.0/bin && make check-format
      run: export PATH=$PATH:/usr/lib/llvm-5.0/bin && clang-format -i -style=file src/context.h src/device.h src/device.c src/logging.c src/logging.h src/nwipe.c src/nwipe.h src/options.c src/options.h src/gui.h src/gui.c src/version.h src/version.c src/method.h src/method.c src/pass.c src/pass.h src/prng.c src/prng.h && git diff-index --quiet HEAD
